# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-29 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0002_accesstoken_is_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='expires',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
