# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-29 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0003_accesstoken_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='is_extended',
        ),
    ]
