# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selectionQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.BinaryField(max_length=1000)),
                ('model', models.CharField(max_length=25)),
                ('table_id', models.CharField(max_length=50)),
                ('miscOptions', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TableRowsSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterApp_consumerKey', models.CharField(blank=True, max_length=255, null=True)),
                ('twitterApp_consumer_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('twitterApp_access_token_key', models.CharField(blank=True, max_length=255, null=True)),
                ('twitterApp_access_token_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('twitterApp_parameters_error', models.BooleanField(default=False)),
                ('twitterUsersToHarvestLimit', models.IntegerField(blank=True, default=30)),
                ('twitterHashtagsToHarvestLimit', models.IntegerField(blank=True, default=5)),
                ('facebookApp_parameters_error', models.BooleanField(default=False)),
                ('facebookPagesToHarvestLimit', models.IntegerField(blank=True, default=20)),
                ('youtubeApp_dev_key', models.CharField(blank=True, max_length=255, null=True)),
                ('youtubeApp_parameters_error', models.BooleanField(default=False)),
                ('ytChannelsToHarvestLimit', models.IntegerField(blank=True, default=100)),
                ('ytPlaylistsToHarvestLimit', models.IntegerField(blank=True, default=5)),
                ('passwordResetToken', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('passwordResetDateLimit', models.DateTimeField(null=True)),
            ],
        ),
    ]
