# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-14 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytchannel',
            name='commentCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ytchannel',
            name='featuredChannel',
            field=models.ManyToManyField(related_name='_ytchannel_featuredChannel_+', to='Youtube.YTChannel'),
        ),
        migrations.AddField(
            model_name='ytchannel',
            name='subscriberCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ytchannel',
            name='videoCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ytchannel',
            name='viewCount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
