# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0002_auto_20160814_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytchannel',
            name='_ident',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
