# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-30 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0002_ytcomment_text_truncated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytcomment',
            name='numberOfReplies',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ytplaylistitem',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlistsSpots', to='Youtube.YTVideo'),
        ),
    ]
