# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0003_auto_20160814_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytchannel',
            name='commentCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ytchannel',
            name='subscriberCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ytchannel',
            name='videoCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ytchannel',
            name='viewCount',
            field=models.IntegerField(null=True),
        ),
    ]
