# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-30 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0003_auto_20160930_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytcomment',
            name='numberOfReplies',
            field=models.IntegerField(default=0),
        ),
    ]
