# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-19 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0004_auto_20160814_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcount',
            name='value',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscribercount',
            name='value',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='value',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ytchannel',
            name='commentCount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ytchannel',
            name='subscriberCount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ytchannel',
            name='viewCount',
            field=models.BigIntegerField(null=True),
        ),
    ]
