# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-30 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0004_auto_20160930_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytcomment',
            name='likeCount',
            field=models.BigIntegerField(default=0),
        ),
    ]
