# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-20 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0005_auto_20160819_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytcomment',
            name='channel',
        ),
    ]
