# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-21 00:30
from __future__ import unicode_literals

import SocialNetworkHarvester_v1p0.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0006_remove_ytcomment_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DislikeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_time', models.DateTimeField(default=SocialNetworkHarvester_v1p0.models.djangoNow)),
                ('value', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_time', models.DateTimeField(default=SocialNetworkHarvester_v1p0.models.djangoNow)),
                ('value', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LikeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_time', models.DateTimeField(default=SocialNetworkHarvester_v1p0.models.djangoNow)),
                ('value', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commentcount',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_counts', to='Youtube.YTVideo'),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Youtube.YTVideo'),
        ),
        migrations.AddField(
            model_name='viewcount',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_counts', to='Youtube.YTVideo'),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='_ident',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='contentRating_raw',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='dislike_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='favorite_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='privacyStatus',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='publicStatsViewable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='publishedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='recordingLocation',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='streamConcurrentViewers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='streamEndTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='streamStartTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commentcount',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_counts', to='Youtube.YTChannel'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Youtube.YTChannel'),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_counts', to='Youtube.YTChannel'),
        ),
        migrations.AddField(
            model_name='likecount',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_counts', to='Youtube.YTVideo'),
        ),
        migrations.AddField(
            model_name='favoritecount',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_counts', to='Youtube.YTVideo'),
        ),
        migrations.AddField(
            model_name='dislikecount',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_counts', to='Youtube.YTVideo'),
        ),
    ]
