# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-22 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0008_auto_20160820_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytvideo',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
