# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-22 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0009_auto_20160822_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytcomment',
            name='video',
        ),
        migrations.AddField(
            model_name='likecount',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_counts', to='Youtube.YTComment'),
        ),
        migrations.AddField(
            model_name='ytchannel',
            name='_last_comment_harvested',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ytcomment',
            name='_deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ytcomment',
            name='_error_on_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ytcomment',
            name='_ident',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ytcomment',
            name='_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ytcomment',
            name='_update_frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ytcomment',
            name='channel_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Youtube.YTChannel'),
        ),
        migrations.AddField(
            model_name='ytcomment',
            name='likeCount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ytcomment',
            name='publishedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ytcomment',
            name='text',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='ytcomment',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ytcomment',
            name='video_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Youtube.YTVideo'),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='_error_on_comment_harvest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ytvideo',
            name='_last_comment_harvested',
            field=models.DateTimeField(null=True),
        ),
    ]
