# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-23 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0010_auto_20160822_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ytvideo',
            name='_error_on_comment_harvest',
        ),
        migrations.RemoveField(
            model_name='ytvideo',
            name='_last_comment_harvested',
        ),
        migrations.AddField(
            model_name='ytchannel',
            name='_error_on_comment_harvest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ytcomment',
            name='_update_frequency',
            field=models.IntegerField(default=2),
        ),
    ]
