# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-23 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0011_auto_20160823_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytchannel',
            name='_earliest_comment_page_token',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ytchannel',
            name='_has_reached_comments_begining',
            field=models.BooleanField(default=False),
        ),
    ]
