# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0013_auto_20160824_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytvideo',
            name='description',
            field=models.CharField(max_length=8192, null=True),
        ),
    ]
