# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0014_auto_20160824_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytcomment',
            name='text',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
