# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0016_subsription'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytchannel',
            name='_last_subs_harvested',
            field=models.DateTimeField(null=True),
        ),
    ]
