# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0017_ytchannel__last_subs_harvested'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytchannel',
            name='_public_subscriptions',
            field=models.BooleanField(default=True),
        ),
    ]
