# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0018_ytchannel__public_subscriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsription',
            new_name='Subscription',
        ),
    ]
