# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-26 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0020_auto_20160825_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytchannel',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
