# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0021_auto_20160825_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytchannel',
            name='_last_playlists_harvested',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ytplaylist',
            name='_ident',
            field=models.CharField(default=datetime.datetime(2016, 9, 12, 21, 31, 30, 375252, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ytplaylist',
            name='_last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ytplaylist',
            name='privacy_status',
            field=models.CharField(default=datetime.datetime(2016, 9, 12, 21, 31, 57, 921828, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ytplaylist',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
