# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0022_auto_20160912_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytplaylist',
            name='privacy_status',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
