# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0024_auto_20160914_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytchannel',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
