# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0025_auto_20160914_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytplaylist',
            name='_error_on_harvest',
            field=models.BooleanField(default=False),
        ),
    ]
