# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0026_ytplaylist__error_on_harvest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ytplaylist',
            old_name='_error_on_harvest',
            new_name='_error_on_update',
        ),
    ]
