# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0027_auto_20160914_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytplaylist',
            name='_last_video_harvested',
            field=models.DateTimeField(null=True),
        ),
    ]
