# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0028_ytplaylist__last_video_harvested'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytplaylist',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
