# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0029_ytplaylist_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytchannel',
            name='title',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
