# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0032_ytplaylist__error_on_harvest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytplaylistitem',
            name='playlistOrder',
            field=models.IntegerField(null=True),
        ),
    ]
