# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0033_auto_20160919_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytvideo',
            name='_file_path',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
